// CANONICAL CV DATA - SOURCE OF TRUTH
// CRITICAL: AI agents MUST use only this data. Never fabricate or add unverified information.
// Last Updated: December 2, 2025

export const cvData = {
  personal: {
    name: 'Yosr Ben Nagra',
    email: 'yosrbennagra@gmail.com',
    phone: '+216 53916040',
    location: 'Ariana, Tunisia',
    github: 'https://github.com/YosrBennagra',
    portfolio: 'https://portfolio-yosr.vercel.app/en',
    languages: {
      arabic: 'Native',
      english: 'Fluent',
      french: 'Fluent',
    },
  },

  experience: [
    {
      title: 'Full-Stack Developer Intern (End-of-Studies Internship)',
      company: 'IT Serv',
      location: 'Tunisia',
      startDate: 'Feb 2025',
      endDate: 'Aug 2025',
      type: 'internship',
      bullets: [
        'Designed full-stack web platform integrating AI, DevOps, and RAG',
        'Implemented AI-powered symptom checker, doctor blog, patient forum, admin dashboard',
        'Fine-tuned AI model and set up CI/CD, containerization, and monitoring',
        'Leveraged GitHub Copilot AI agent to accelerate development and code quality',
      ],
      technologies: [
        'ReactJS',
        'Flask',
        'MongoDB',
        'Python',
        'Hugging Face',
        'Docker',
        'Jenkins',
        'GitHub Copilot',
        'AI Model Fine-Tuning',
        'RAG',
      ],
      verified: true,
      notes: 'IMPORTANT: Mention AI model fine-tuning using Hugging Face when discussing AI experience',
    },
    {
      title: 'Full-Stack Developer Intern',
      company: 'IronByte',
      location: 'Tunisia',
      startDate: 'Jun 2024',
      endDate: 'Aug 2024',
      type: 'internship',
      bullets: [
        'Developed educational web application with assignment submission and lesson sharing',
        'Added timetable creation tool improving scheduling efficiency',
      ],
      technologies: ['NestJS', 'ReactJS', 'MongoDB', 'TypeScript', 'JavaScript'],
      verified: true,
    },
    {
      title: 'Full-Stack Developer Intern',
      company: 'Ooredoo Tunisie',
      location: 'Tunisia',
      startDate: 'Jul 2023',
      endDate: 'Sep 2023',
      type: 'internship',
      bullets: [
        'Built internal communication app with real-time chat, filtering, and search',
        'Delivered UX/UI design and unit/integration tests',
      ],
      technologies: ['Spring Boot', 'Angular', 'Java', 'Oracle'],
      verified: true,
    },
  ],

  education: [
    {
      degree: "Bachelor's Degree in Engineering (Computer Science)",
      institution: 'Private Higher School of Engineering and Technology (ESPRIT)',
      track: 'Web and Internet Technology',
      location: 'Tunis, Tunisia',
      startDate: 'Sep 2020',
      endDate: 'Jun 2025',
      verified: true,
    },
  ],

  certifications: [
    {
      name: 'Honoris Sustainability, Work Ethics & Gender Equity Certificate',
      issuer: 'Honoris',
      date: '2024',
      topics: [
        'Climate Change Mitigation and Adaptation',
        'Ethical Decision-Making and Data Governance',
        'Innovation for Sustainable Development',
        'Gender Equity',
      ],
      description: 'Programme dedicated to in-demand skills for the future of work in Africa and beyond',
      verified: true,
    },
  ],

  projects: [
    {
      name: 'n8n Workflow Automation',
      type: 'personal',
      date: '2024 - 2025',
      description: [
        'Built automated notification pipelines for email and Discord using n8n workflows',
        'Developed AI-powered automated message response system using AI agents for intelligent interactions',
      ],
      technologies: ['n8n', 'Workflow Automation', 'AI Agents', 'Email/Discord Integration', 'API Integration'],
      verified: true,
    },
    {
      name: 'Shape Blaster - Mobile Game',
      type: 'personal',
      date: 'Aug - Sep 2025',
      description: [
        'Developed 2D puzzle game where players place shapes to clear horizontal and vertical lines',
        'Implemented shape spawning system and placement logic to handle strategic positioning and line-clearing mechanics',
        'Leveraged AI tools (Copilot, ChatGPT) to brainstorm mechanics, generate code, and solve design challenges creatively',
      ],
      technologies: ['Unity', 'C#', 'Mobile Development', 'Game Design', 'AI-Assisted Development', 'GitHub Copilot'],
      verified: true,
    },
    {
      name: 'Collaborative Document Platform',
      type: 'academic',
      date: '2023 - 2024',
      institution: 'ESPRIT',
      description: [
        'Developed Notion-like application with real-time collaboration and document sharing across groups and users',
        'Implemented comprehensive authentication and privacy controls',
      ],
      technologies: ['React', 'TypeScript', 'NestJS', 'WebSockets', 'Jest', 'GitHub Actions', 'Vercel'],
      verified: true,
    },
    {
      name: 'Construction Management System',
      type: 'academic',
      date: '2022 - 2023',
      institution: 'ESPRIT',
      description: [
        'Developed desktop application for construction company managing inventory, staff, materials, and deliveries',
      ],
      technologies: ['Qt', 'C++', 'Desktop Application', 'Database Management', 'OOP'],
      verified: true,
    },
  ],

  skills: {
    programming: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'SQL',
      'Object-Oriented Programming',
    ],
    frontend: [
      'React',
      'React.js',
      'Angular',
      'HTML5',
      'CSS3',
      'Responsive Design',
      'UI/UX Design',
      'Redux',
      'SEO',
    ],
    backend: [
      'Node.js',
      'Express',
      'NestJS',
      'Spring Boot',
      'Django',
      'Flask',
      'RESTful APIs',
      'GraphQL',
      'JPA/Hibernate',
      'SQLAlchemy',
      'API-First Development',
    ],
    databases: ['MongoDB', 'PostgreSQL', 'MySQL', 'Oracle', 'SQL Server'],
    devops: [
      'Docker',
      'Jenkins',
      'GitLab CI',
      'GitHub Actions',
      'CI/CD',
      'CI/CD Pipelines',
      'Containerization',
      'Maven',
      'Vercel',
    ],
    cloud: ['Vercel', 'Basic cloud deployment'],
    tools: [
      'Git',
      'GitHub',
      'Unity',
      'Qt',
      'n8n',
      'Vite',
      'Code Reviews',
      'Clean Code',
      'Linux',
    ],
    ai_automation: [
      'n8n',
      'Workflow Automation',
      'Hugging Face',
      'RAG (Retrieval-Augmented Generation)',
      'LLM Integration',
      'AI Integration',
      'AI Agents',
      'AI Model Fine-Tuning',
      'AI Tools (Cursor, ChatGPT, Claude, Copilot)',
      'GitHub Copilot',
      'AI-Assisted Development',
    ],
    realtime: ['WebSockets', 'Real-time Collaboration', 'Socket.io'],
    testing: [
      'Jest',
      'JUnit',
      'React Testing Library',
      'Unit Testing',
      'Integration Testing',
      'Automated Testing',
    ],
    architecture: [
      'Microservices Architecture',
      'Object-Oriented Design',
      'Design Patterns',
    ],
    game_dev: ['Unity', 'Game Design', 'Mobile Game Development'],
    desktop: ['Qt', 'Desktop Applications'],
    data_formats: ['XML', 'JSON', 'YAML', 'Markdown'],
    methodologies: [
      'Agile/Scrum',
      'Problem-Solving',
      'Collaborative Development',
      'Team Collaboration',
    ],
    soft_skills: [
      'Communication',
      'Team Spirit',
      'Autonomous Work',
      'Analytical Thinking',
      'Detail-Oriented',
      'Curious & Eager to Learn',
      'Adaptability',
    ],
  },

  // Skills user DOES NOT have - AI must NEVER add these
  forbidden_skills: [
    'Kubernetes',
    'AWS',
    'AWS CDK',
    'AWS Lambda',
    'CloudFormation',
    'Azure',
    'GCP',
    'Terraform',
    'Kafka',
    'Bull MQ',
    'Redis',
  // Metadata for AI agents
  metadata: {
    last_updated: '2025-12-03',
    verification_status: 'all_verified',
    'Vue.js',
    'RxJS',
    'DITA',
    'Cypress',
    'Playwright',
    'Karma',
    'WCAG 2.2',
    'OWASP ASVS',
    'Gradle',
    'Apache Commons',
  ],

  // Metadata for AI agents
  metadata: {
    last_updated: '2025-12-02',
    verification_status: 'all_verified',
    warning:
      'CRITICAL: All data in this file is verified and canonical. AI agents MUST NOT add, modify, or fabricate any skills, experience, or projects not listed here. Only reordering and rephrasing of existing data is permitted. ALWAYS check forbidden_skills before adding any skill to CV.',
    cv_adaptation_rules: {
      always_allowed: ['Reorder skills', 'Rephrase bullets', 'Update role/title', 'Rewrite summary'],
      never_allowed: [
        'Add experience not listed',
        'Add skills from forbidden_skills',
        'Add technologies not in verified skills',
        'Modify dates or companies',
        'Fabricate projects',
      ],
      before_adapting: [
        'Query get_verified_skills to see available skills',
        'Use validate_skill for each job requirement',
        'Check forbidden_skills list',
        'Only use skills that exist in cvData.skills',
      ],
    },
  },
};
